 # Docker Image
image: python:3-alpine

# Abhängigkeiten installieren
before_script:
    - apk add --no-cache git
    - apk add --no-cache py3-pytest
    - pip install -r requirements.txt

# Festlegen der Stages
stages:
  - test

# Unit Tests für Versuch1 durchführen
testAss01:
  stage: test
  variables:
    CI_BUILDS_DIR: assignments/assignment01
  rules:
    - changes:
      - "$CI_BUILDS_DIR/*.py"
  script:
    - cd $CI_BUILDS_DIR
    - pytest test_ass01.py --junitxml=report01.xml
  # JUnit Report
  artifacts:
    when: always
    reports:
      junit: $CI_BUILDS_DIR/report01.xml


# Unit Tests für Assignemnt 2 durchführen
testAss02:
  stage: test
  variables:
    CI_BUILDS_DIR: assignments/assignment02
  rules:
    - changes:
      - "$CI_BUILDS_DIR/*.py"
  script:
    - cd $CI_BUILDS_DIR
    - pytest test_ass02.py --junitxml=report02.xml
  # JUnit Report
  artifacts:
    when: always
    reports:
      junit: $CI_BUILDS_DIR/report02.xml

# Unit Tests für Assignemnt 3 durchführen
testAss03:
  stage: test
  variables:
    CI_BUILDS_DIR: assignments/assignment03
  rules:
    - changes:
      - "$CI_BUILDS_DIR/*.py"
  script:
    - cd $CI_BUILDS_DIR
    - pytest test_ass03.py --junitxml=report03.xml
  # JUnit Report
  artifacts:
    when: always
    reports:
      junit: $CI_BUILDS_DIR/report03.xml

# Unit Tests für Assignemnt 4 durchführen
testAss04:
  stage: test
  variables:
    CI_BUILDS_DIR: assignments/assignment04
  rules:
    - changes:
      - "$CI_BUILDS_DIR/*.py"
  script:
    - cd $CI_BUILDS_DIR
    - pytest test_ass04.py --junitxml=report04.xml
  # JUnit Report
  artifacts:
    when: always
    reports:
      junit: $CI_BUILDS_DIR/report04.xml


# Unit Tests für Assignemnt 5 durchführen
testAss05:
  stage: test
  variables:
    CI_BUILDS_DIR: assignments/assignment05
#  rules:
#    - changes:
#      - "$CI_BUILDS_DIR/*.py"
  script:
    - cd $CI_BUILDS_DIR
    - pytest test_ass05.py --junitxml=report05.xml
  # JUnit Report
  artifacts:
    when: always
    reports:
      junit: $CI_BUILDS_DIR/report05.xml
