 # Docker Image
image: python:3-alpine

# Abhängigkeiten installieren
before_script:
    - apk add --no-cache git
    - apk add --no-cache py3-pytest
    - pip install -r requirements.txt

# Festlegen der Stages
stages:
  - test

# Unit Tests für Versuch1 durchführen
testAss01:
  stage: test
  variables:
    CI_BUILDS_DIR: assignments/assignment01
  rules:
    - changes:
      - "$CI_BUILDS_DIR/*.py"
  script:
    - cd $CI_BUILDS_DIR
    - pytest test_ass01.py --junitxml=report01.xml
  # JUnit Report
  artifacts:
    when: always
    reports:
      junit: $CI_BUILDS_DIR/report01.xml


# Unit Tests für Versuch1 durchführen
testAss02:
  stage: test
  variables:
    CI_BUILDS_DIR: assignments/assignment02
#  rules:
#    - changes:
#      - "$CI_BUILDS_DIR/*.py"
  script:
    - cd $CI_BUILDS_DIR
    - pytest test_ass02.py --junitxml=report02.xml
  # JUnit Report
  artifacts:
    when: always
    reports:
      junit: $CI_BUILDS_DIR/report02.xml

